# Подготовка данных

**Виды**

Машинное обчение можно разделить на несколько больших категорий:

*Обучение с учителем*

Обучение с учителем (или управляемое обучение). Здесь данные представлены вместе с дополнительными признаками, которые мы хотим предсказать. Это может быть любая из следующих задач:
1. классификация: выборки данных принадлежат к двум или более классам и мы хотим научиться на уже размеченных данных предсказывать класс неразмеченной выборки. Примером задачи классификации может стать распознавание рукописных чисел, цель которого — присвоить каждому входному набору данных одну из конечного числа дискретных категорий. Другой способ понимания классификации — это понимание ее в качестве дискретной (как противоположность непрерывной) формы управляемого обучения, где у нас есть ограниченное количество категорий, предоставленных для N выборок; и мы пытаемся их пометить правильной категорией или классом.
2. регрессионный анализ: если желаемый выходной результат состоит из одного или более непрерывных переменных, тогда мы сталкиваемся с регрессионным анализом. Примером решения такой задачи может служить предсказание длинны лосося как результата функции от его возраста и веса.


*Обучение без учителя*

Обучение без учителя (или самообучение). В данном случае обучающая выборка состоит из набора входных данных Х без каких-либо соответствующих им значений. Целью подобных задач может быть определение групп схожих элементов внутри данных. Это называется кластеризацией или кластерным анализом. Также задачей может быть установление распределения данных внутри пространства входов, называемое густотой ожидания (density estimation). Или это может быть выделение данных из высоко размерного пространства в двумерное или трехмерное с целью визуализации данных.

**Обучающая выборка и контрольная выборка**

Машинное обучение представляет собой обучение выделению некоторых свойств выборки данных и применение их к новым данным. Вот почему общепринятая практика оценки алгоритма в Машинном обучении — это разбиение данных вручную на два набора данных. Первый из них — это обучающая выборка, на ней изучаются свойства данных. Второй — контрольная выборка, на ней тестируются эти свойства.

# Пример: анализ выборки

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('https://stepik.org/media/attachments/course/57984/titanic.csv', index_col=0)

In [ ]:
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.columns

Index(['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket',
       'Fare', 'Cabin', 'Embarked'],
      dtype='object')

<b>Survived</b> - Выжил (0 = No, 1 = Yes) <br>
<b>Pclass</b>  - Класс билета (1 = 1st, 2 = 2nd, 3 = 3rd)<br>
<b>Sex</b>  - Пол (male = мужчина, female = женщина)	<br>
<b>Age</b>  - Возраст в годах <br>
<b>SibSp</b>  - Кол-во сестер/братьев/жен/мужей на Титанике 	<br>
<b>Parch</b>  - Кол-во родителей/детей на Титанике	<br>
<b>Ticket</b>  - Номер билета	<br>
<b>Fare</b>  - Плата за проезд 	<br>
<b>Cabin</b>  - Номер каюты 	<br>
<b>Embarked</b>  - 	Порт погрузки (C = Cherbourg, Q = Queenstown, S = Southampton)<br>

**Анализ данных**

In [ ]:
df.shape

(891, 11)

In [ ]:
df.dtypes

Survived      int64
Pclass        int64
Name         object
Sex          object
Age         float64
SibSp         int64
Parch         int64
Ticket       object
Fare        float64
Cabin        object
Embarked     object
dtype: object

In [ ]:
# Статистика
df.describe()

         Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

Посмотрим, кого больше на борту: женщин или мужчин?

In [ ]:
import seaborn as sns

In [ ]:
sns.set(style="ticks")
sns.countplot('Sex', data=df)

TypeError: ignored

Разделим эту статистику по классам

In [ ]:
sns.catplot('Pclass', data=df, hue='Sex', kind='count')

Узнаем сколько детей путешествовало на титанике

In [ ]:
df['Person'] = df.Sex
df.loc[df['Age'] < 16, 'Person'] = 'Child'

In [ ]:
sns.catplot('Pclass', data=df, hue='Person', kind='count')

Изобразим распределение по возрастам

In [ ]:
df.Age.hist(bins=60)

In [ ]:
# Еще один способ визуализировать данные - FacetGrid

fig = sns.FacetGrid(df, hue="Sex", aspect=4)
fig.map(sns.kdeplot, 'Age', shade=True)

fig.set(xlim=(0, df['Age'].max()))

fig.add_legend()

In [ ]:
# Тоже самое с классом билета

fig = sns.FacetGrid(df, hue="Pclass",aspect=4)
fig.map(sns.kdeplot, 'Age', shade=True)

fig.set(xlim=(0, df['Age'].max()))

fig.add_legend()

In [ ]:
df.sort_values(by='Ticket').head()

Билеты имеют какой-то странный формат<br>
Видно, что по одному номеру билета путешествовало сразу несколько людей, причем часто — с разными фамилиями

In [ ]:
df.Cabin[df.Cabin.notna()].unique()

In [ ]:
df[df.Cabin.isin(['C23 C25 C27','B96 B98'])]

Номера кают прописаны мало у когo<br>
В существующих номерах кают прописан код палубы

In [ ]:
levels = []
for level in df['Cabin'].dropna():
    levels.append(level[0])

cabin_df = pd.DataFrame(levels)
cabin_df.columns = ['Cabin']
cabin_df.sort_values(by='Cabin', inplace=True)
sns.countplot('Cabin', data=cabin_df, palette='winter_d')

In [ ]:
cabin_df = cabin_df[cabin_df.Cabin != 'T']
sns.countplot('Cabin', data=cabin_df, palette='summer_d')

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.figure(figsize=(5, 6))
sns.countplot('Embarked', data=df, hue='Pclass', order=['C', 'Q', 'S'])

In [ ]:
df.sort_values(by='Name').head()

Отсортировав по имени, получаем, что многие путешествовали семьями, часто семьи оказались разделены, выжила лишь часть

In [ ]:
df['Family'] = df.Parch + df.SibSp

In [ ]:
df['Is_Alone'] = df.Family == 0

In [ ]:
sns.countplot('Is_Alone', hue='Survived', data=df)

In [ ]:
df.describe()['Fare']

In [ ]:
import numpy as np

In [ ]:
bins = [-1]
bins = np.append(bins, df.describe()['Fare'][4:-1].values)
bins = np.append(bins, df['Fare'].max())
bins

In [ ]:
df['Category_fare'] = pd.cut(df['Fare'], bins=bins, labels=['Low', 'Mid', 'High_Mid', 'High'])

In [ ]:
df.head()

In [ ]:
sns.catplot('Category_fare', hue='Survived', data=df, kind='count')

In [ ]:
sns.catplot('Embarked', hue='Survived', data=df, kind='count')

# Пример: подготовка данных

Обработка пропущенных значений

In [ ]:
# Количество строк с пропущенными значениями
df.isna().sum()

In [ ]:
sns.heatmap(df.isnull(), cbar = False).set_title("Пропущенные значения");

In [ ]:
df.Embarked.mode()

Заполним нулями пропущенные значения

In [ ]:
df.Embarked.fillna(df.Embarked.mode()[0], inplace = True)

In [ ]:
df.Cabin = df.Cabin.fillna('NA')

In [ ]:
df['Salutation'] = df.Name.apply(lambda x: x.split(',')[1].split('.')[0].strip())

In [ ]:
df.head()

In [ ]:
grp = df.groupby(['Sex', 'Pclass', 'Salutation'])
df.Age = grp.Age.apply(lambda x: x.fillna(x.median()))
# df.Age.fillna(df.Age.median, inplace = True)

In [ ]:
grp.Age.median()

In [ ]:
df.loc[[1, 878, 879, 889]]

In [ ]:
Y = df['Survived']
X = df[df.columns[1:]]

In [ ]:
X['Deck'] = X.Cabin.str[0]

In [ ]:
X.head()

Переведем поля Sex, Embarked, Cabin в числа

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
X['Sex'] = le.fit_transform(X['Sex'])

In [ ]:
le.classes_

In [ ]:
X['Cabin'] = LabelEncoder().fit_transform(X['Cabin'])
X['Embarked'] = LabelEncoder().fit_transform(X['Embarked'])

In [ ]:
X.head()

In [ ]:
pd.get_dummies(X.Category_fare, prefix="Fare").head()

In [ ]:
pd.concat([X, pd.get_dummies(X.Category_fare, prefix="Fare")], axis=1).head()

In [ ]:
X.columns

Будем использовать только значимые поля

In [ ]:
cols = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Cabin', 'Embarked']

In [ ]:
# Разделяем выборку на обучающую и тестовую

from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X[cols], Y, test_size=0.2, random_state=0)

print(X_train.shape, X_test.shape)