In [ ]:
"""
Задание 2. Задача регрессии

Для набора данных "diamonds" из пакета seaborn:

1)Загрузите данные. 
    Изучите набор данных, есть хорошая зависимость между числом карат бриллианта и его тремя x, y, z размерами.
2)Создайте новый поднабор данных df1 = df[['x', 'y', 'z', 'carat']] и очистите его от выбросов на основе ящика с усами.
3)Полученный набор данных разделите на тренировочную и тестовую выборку, обучите kNN регрессор и оцените точность модели. 
    Используйте все известные Вам метрики оценки качества решения задачи регрессии (3 балла).
"""

In [1]:
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
#  Пунтк 1
"""
Данные содержат информацию о бриллиантах: 
    масса в каратах (carat), цена, качество огранки, цвет, чистота и геометрические размеры (x, y, z).
Видим, что carat сильно связан с x, y, z → физический смысл: чем больше размеры, тем больше масса (в каратах).
""" 
df = sns.load_dataset('diamonds')
df.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [ ]:
"""
"""
df.corr(numeric_only=True)['carat']

carat    1.000000
depth    0.028224
table    0.181618
price    0.921591
x        0.975094
y        0.951722
z        0.953387
Name: carat, dtype: float64

In [ ]:
# 2 - Создание поднабора данных и поиск выбросов
df1 = df[['x', 'y', 'z', 'carat']]

In [6]:
df1.describe().T

         count      mean       std  min   25%   50%   75%    max
x      53940.0  5.731157  1.121761  0.0  4.71  5.70  6.54  10.74
y      53940.0  5.734526  1.142135  0.0  4.72  5.71  6.54  58.90
z      53940.0  3.538734  0.705699  0.0  2.91  3.53  4.04  31.80
carat  53940.0  0.797940  0.474011  0.2  0.40  0.70  1.04   5.01

In [7]:
# 3 - Очистка от выбросов по методу "ящика с усами" (IQR)
Q1 = df1.quantile(0.25)
Q3 = df1.quantile(0.75)
IQR = Q3 - Q1

outliers = (df1 < (Q1 - 1.5 * IQR)) | (df1 > (Q3 + 1.5 * IQR))
df2 = df1[~outliers.any(axis=1)]

In [10]:
# 4 - Разделение на обучающую и тестовую выборки
from sklearn.model_selection import train_test_split

X = df2[['x','y','z']]
y = df2['carat']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=12)

In [11]:
# 5 - Обучение kNN-регрессора
from sklearn.neighbors import KNeighborsRegressor

knn_model = KNeighborsRegressor(n_neighbors=5).fit(X_train, y_train)

In [12]:
# 6 - Метрики оценки качества модели
score_knn = knn_model.score(X_test, y_test)

In [13]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

y_pred = knn_model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R²:", r2)

MAE: 0.00809378303065245
MSE: 0.00019179244739117904
RMSE: 0.013848915025776534
R²: 0.9988324283388264